name: Build and Deploy Frontend

on:
  push:
    branches:
      - develop
      - staging
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 821589437001.dkr.ecr.ap-south-1.amazonaws.com
  ECR_REPOSITORY: midnight-bites-frontend
  EKS_K8S_REPO: Pratikbhosale7491/midnight-bites-k8s

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
            echo "VALUES_FILE=environments/production/values-frontend.yaml" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "staging" ]; then
            echo "ENVIRONMENT=staging" >> $GITHUB_ENV
            echo "VALUES_FILE=environments/staging/values-frontend.yaml" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
            echo "VALUES_FILE=environments/dev/values-frontend.yaml" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$ENVIRONMENT-latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$ENVIRONMENT-latest
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update image tag in k8s repo
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git clone https://$GIT_TOKEN@github.com/$EKS_K8S_REPO.git
          cd midnight-bites-k8s
          sed -i "s|tag:.*|tag: \"$IMAGE_TAG\"|g" $VALUES_FILE
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git diff --staged --quiet || git commit -m "ci: update $ENVIRONMENT mb-frontend image to $IMAGE_TAG"
          git push